# Generated by Django 4.2.23 on 2026-04-09 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "answer_id",
                    models.IntegerField(
                        db_column="Answer_ID", primary_key=True, serialize=False
                    ),
                ),
                ("link", models.CharField(db_column="Link", max_length=255, null=True)),
                (
                    "page_num",
                    models.IntegerField(blank=True, db_column="PageNum", null=True),
                ),
                ("text", models.CharField(db_column="Answer", max_length=255)),
                ("last_day_scraped", models.DateField(db_column="LastDayScraped")),
                (
                    "copyright_date",
                    models.DateField(blank=True, db_column="CopyrightDate", null=True),
                ),
                (
                    "outdated_flag",
                    models.IntegerField(
                        blank=True, db_column="OutdatedFlag", null=True
                    ),
                ),
                (
                    "flag_new_answer_id",
                    models.IntegerField(
                        blank=True, db_column="FlagNewAnswerID", null=True
                    ),
                ),
                (
                    "answer_rating",
                    models.IntegerField(
                        blank=True, db_column="AnswerRating", null=True
                    ),
                ),
                (
                    "validity_level",
                    models.IntegerField(
                        choices=[
                            (1, "Random/Unverified"),
                            (2, "Sourced"),
                            (3, "Published/audited/GovData"),
                        ],
                        db_column="AnswerValid",
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "lmforge_core_answer",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("is_user", models.BooleanField(default=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lmforge_core_conversation",
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "license_id",
                    models.IntegerField(
                        db_column="License_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "license_name",
                    models.CharField(db_column="License_Name", max_length=255),
                ),
                ("license_valid", models.BooleanField(db_column="License_Valid")),
                (
                    "validity_level",
                    models.IntegerField(
                        choices=[
                            (1, "Random/Unverified"),
                            (2, "Sourced"),
                            (3, "Published/audited/GovData"),
                        ],
                        db_column="LicenseValid",
                        default=1,
                    ),
                ),
            ],
            options={
                "db_table": "lmforge_core_license",
            },
        ),
        migrations.CreateModel(
            name="ModelStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("dataset", models.CharField(max_length=255)),
                ("ROUGE1", models.FloatField()),
                ("ROUGE2", models.FloatField()),
                ("ROUGE_L", models.FloatField()),
                ("ROUGE_LSum", models.FloatField()),
                ("BERTScoreF1", models.FloatField()),
                ("BERTScorePrecision", models.FloatField()),
                ("BERTScoreRecall", models.FloatField()),
                ("STSScore", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lmforge_core_modelstats",
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "question_id",
                    models.AutoField(
                        db_column="Question_ID", primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(db_column="Question", max_length=255)),
            ],
            options={
                "db_table": "lmforge_core_question",
            },
        ),
        migrations.CreateModel(
            name="Reviewer",
            fields=[
                (
                    "review_id",
                    models.AutoField(
                        db_column="review_id", primary_key=True, serialize=False
                    ),
                ),
                (
                    "first_name",
                    models.CharField(db_column="first_name", max_length=255),
                ),
                ("last_name", models.CharField(db_column="last_name", max_length=255)),
            ],
            options={
                "db_table": "lmforge_core_reviewer",
            },
        ),
        migrations.CreateModel(
            name="SourceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("file_type", models.CharField(max_length=50)),
                ("content", models.TextField(blank=True, null=True)),
                ("binary_content", models.BinaryField(blank=True, null=True)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("title", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "lmforge_core_scrapeddata",
            },
        ),
        migrations.CreateModel(
            name="SourceDocumentMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=500)),
                ("file_type", models.CharField(max_length=50)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("created_at", models.DateTimeField()),
                (
                    "content_preview",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "source_document",
                    models.OneToOneField(
                        db_column="scraped_data_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="studio.sourcedocument",
                    ),
                ),
            ],
            options={
                "db_table": "lmforge_core_scrapeddatameta",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "source_id",
                    models.CharField(
                        db_column="SourceID",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_name",
                    models.CharField(db_column="SourceName", max_length=255),
                ),
                (
                    "source_description",
                    models.CharField(db_column="SourceDescription", max_length=255),
                ),
                (
                    "source_link",
                    models.CharField(db_column="SourceLink", max_length=255),
                ),
                (
                    "validity_level",
                    models.IntegerField(
                        choices=[
                            (1, "Random/Unverified"),
                            (2, "Sourced"),
                            (3, "Published/audited/GovData"),
                        ],
                        db_column="SourceValid",
                        default=1,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        db_column="License_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.license",
                    ),
                ),
            ],
            options={
                "db_table": "lmforge_core_source",
            },
        ),
        migrations.CreateModel(
            name="ReviewAnswer",
            fields=[
                (
                    "review_answer_id",
                    models.AutoField(
                        db_column="RevAnswer_ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "score_scale",
                    models.IntegerField(
                        db_column="ScoreScale",
                        help_text="Rating between 1 (worst) and 5 (best)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="Description", max_length=255),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.question",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        db_column="reviewer",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.reviewer",
                    ),
                ),
            ],
            options={
                "db_table": "lmforge_core_reviewanswer",
            },
        ),
        migrations.CreateModel(
            name="ProcessedDocument",
            fields=[
                (
                    "doc_id",
                    models.CharField(
                        db_column="DocID",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(db_column="DocDescription", max_length=255),
                ),
                ("link", models.CharField(db_column="DocLink", max_length=255)),
                ("last_date_scraped", models.DateField(db_column="LastDateScraped")),
                ("name", models.CharField(db_column="DocName", max_length=255)),
                (
                    "requires_attribution",
                    models.BooleanField(db_column="RequiresAttribution"),
                ),
                (
                    "validity_level",
                    models.IntegerField(
                        choices=[
                            (1, "Random/Unverified"),
                            (2, "Sourced"),
                            (3, "Published/audited/GovData"),
                        ],
                        db_column="DocValid",
                        default=1,
                    ),
                ),
                (
                    "license",
                    models.ForeignKey(
                        db_column="License_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.license",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_column="Source_ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.source",
                    ),
                ),
            ],
            options={
                "db_table": "lmforge_core_document",
            },
        ),
        migrations.CreateModel(
            name="DatasetArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        db_column="answer_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.answer",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        db_column="question_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studio.question",
                    ),
                ),
            ],
            options={
                "db_table": "lmforge_core_questionanswer",
            },
        ),
        migrations.AddField(
            model_name="answer",
            name="document",
            field=models.ForeignKey(
                db_column="Doc_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="studio.processeddocument",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="license",
            field=models.ForeignKey(
                db_column="License_ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="studio.license",
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                db_column="Question_ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="studio.question",
            ),
        ),
    ]
